### ISSUE TITLE
Just wanted to shout-out: "Thank you."

### ISSUE THREAD

**Issue by leycec** [peterhinch/micropython-msgpack#2]
Obviously, this is *not* an actual issue. :wink: 

I just wanted to extend my personal gratitude for the impressive work you do – both here and on the MicroPython forums. Because of that work, we're likely to adopt your MessagePack implementation (probably in frozen byte-compiled form – gotta minimize that RAM consumption, right?) over MicroPython's standard `ujson` module. The mission has been accomplished.

We're *especially* excited by [these three hot advantages](https://forum.micropython.org/viewtopic.php?f=14&t=10916):

* **Ease of extension.** The repo includes a module which extends support to `tuple`, `set` and `complex` types. It can readily be extended to support other native and library types.
* **A class decorator** enables user classes to be written so that instances can packed and unpacked in exactly the same way as native types.
* **Asynchronous decoding of data** which arrives on a slow or sporadic interface such as a UART or a socket.

I'd expect this project to explode in interest over the coming months. Take all our GitHub stars, Peter! :star:

**Comment by peterhinch** [comment]
Thank you!
